USE [master]
GO
/****** Object:  Database [3m_dashboard_db]    Script Date: 12/12/2020 4:52:48 PM ******/
CREATE DATABASE [3m_dashboard_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'3m_dashboard_db', FILENAME = N'/var/opt/mssql/data/3m_dashboard_db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'3m_dashboard_db_log', FILENAME = N'/var/opt/mssql/data/3m_dashboard_db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [3m_dashboard_db] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [3m_dashboard_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [3m_dashboard_db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET ARITHABORT OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [3m_dashboard_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [3m_dashboard_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET  DISABLE_BROKER 
GO
ALTER DATABASE [3m_dashboard_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [3m_dashboard_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET RECOVERY FULL 
GO
ALTER DATABASE [3m_dashboard_db] SET  MULTI_USER 
GO
ALTER DATABASE [3m_dashboard_db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [3m_dashboard_db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [3m_dashboard_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [3m_dashboard_db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [3m_dashboard_db] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'3m_dashboard_db', N'ON'
GO
ALTER DATABASE [3m_dashboard_db] SET QUERY_STORE = OFF
GO
USE [3m_dashboard_db]
GO
/****** Object:  Table [dbo].[production_target_output]    Script Date: 12/12/2020 4:52:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[production_target_output](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[datetime_stamp] [datetime] NOT NULL,
	[mc_id] [int] NOT NULL,
	[target] [int] NOT NULL,
	[output] [int] NOT NULL,
 CONSTRAINT [PK_production_target_output] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [3m_dashboard_db] SET  READ_WRITE 
GO
CREATE LOGIN sammdbu WITH PASSWORD = '8fdKJl3$nlNv3049jsKK';  
GO
ALTER AUTHORIZATION ON DATABASE::[3m_dashboard_db] TO [sammdbu]
GO
