# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mcr.microsoft.com/dotnet/core/sdk:3.0

pipelines:
  default:
    - step:
        deployment: Test
        caches:
          - dotnetcore
        script:
          - pipe: atlassian/ftp-deploy:0.3.0
            variables:
              USER: 'psec_ftp'
              PASSWORD: '4dev@psec'
              SERVER: '103.70.6.198'
              REMOTE_PATH: '/dev'
              # LOCAL_PATH: '<string>' # Optional
              # DEBUG: '<boolean>' # Optional
              # EXTRA_ARGS: '<string>' # Optional.
              # DELETE_FLAG: '<boolean>' # Optional.

